title: Finn Lim
description: Quantitative Research / Data Scientist
url: https://finnlimjc.github.io
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
author:
  name: Finn Lim
  bio: Quantitative Research / Data Scientist
  location: Singapore
  links:
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/finnljc
    - label: Medium
      icon: fab fa-fw fa-medium
      url: https://medium.com/@finn_lim
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/finnlimjc
footer:
  links:
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/finnljc
    - label: Medium
      icon: fab fa-fw fa-medium
      url: https://medium.com/@finn_lim
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/finnlimjc
atom_feed:
  hide: true
skills:
  - Python
  - SQL
  - AWS
  - R
  - Microsoft Excel
  - Power BI
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
