title: Finn Lim
description: Quantitative Research / Data Scientist
url: https://finnlimjc.github.io
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
author:
  name: Finn Lim
  bio: Quantitative Research / Data Scientist
  location: Singapore
  employer: Postgraduate Student
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/finnlimjc
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      classes: wide
